name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          USERNAME: yjh701701
          ANOTHER_TOKEN: ${{ secrets.TOKEN }}
          
      - name: Commit & Push
        run: |
          git config user.name JuHeon
          git config user.email yjh701701@naver.com
          git add -A .
          git commit -m "3DautoCommit"
          git push origin main

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: "Automated Pull Request"
#          title: "Automated Pull Request"
#          body: "This is an automated pull request."
#          branch: feature-branch
